### ISSUE TITLE
Biocore project status levels

### ISSUE THREAD

**Issue by jfass** [amschaal/glims#15]
possible naming scheme (all are reversible / editable):

1) Data Available
2) QA/QC Finished
3) Being Analyzed
4) Needs Customer Feedback
5) Archived

... handle like Gannt chart tasks, or no?

**Comment by amschaal** [comment]
Available statuses are now configurable by Project type (as well as Sample, Pool, etc) for admins.  I've created a widget for selecting the status on either the individual project page, or from the project list page.

I think the Gannt style tasks may eventually be a separate plugin.
