### ISSUE TITLE
In create lab

### ISSUE THREAD

**Issue by msettles** [amschaal/glims#19]
Under Affiliation, selected "University of California" and received error
"Ensure this value has at most 20 characters (it has 24)." 

<img width="1119" alt="screen shot 2016-07-29 at 6 38 13 am" src="https://cloud.githubusercontent.com/assets/649446/17249961/25a36b5a-5557-11e6-9079-ff5e2bac66ed.png">

**Comment by amschaal** [comment]
Why that's mighty stingy! I made the change in the code.  It will come through with the next commit and roll into the test server later today.
