### ISSUE TITLE
Duplicate "Accounts" tabs on Project page

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#20]
![glims_screenshot - 08102016 - 03 02 14 pm](https://cloud.githubusercontent.com/assets/2992433/17572940/0a5f237a-5f0c-11e6-8c27-cebea5a12184.png)

The uploaded file shows that there are two identical "Accounts" tabs.

Monica

**Comment by monicabritton** [comment]
Ignore the previous screenshot (of the wrong screen!)  This one should be illustrative of the duplicate "Accounts" tab:
![glims_screenshot - 08102016 - 03 02 14 pm](https://cloud.githubusercontent.com/assets/2992433/17572906/e8878f94-5f0b-11e6-8df5-43779b2fa6c2.png)

**Comment by amschaal** [comment]
The plugin was misconfigured.  Not related to the code.
