### ISSUE TITLE
Filter (or search) for projects others are participating in

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#24]
Currently, projects can be filtered based on "Manager".  It would be useful to also be able to search/filter for participants.  This could answer such questions as "Which projects is our statistician involved with?"  or  "Which projects is John Doe doing the library prep for?"

Thanks!

M

**Comment by amschaal** [comment]
I would propose that participants, in addition to being another filter, be another column on the projects page.  The concern seems to be that there might be too many columns.  This could be resolved by having columns be configurable.  I'll have to do some research to see how much work this would be.
