### ISSUE TITLE
Add project-specific contact info

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#28]
In the project details, it would be helpful to have a "project contact info" field.  This could be optional, since for many projects, the PI is the contact.  However, when the main contact (for samples, analysis, etc.) is someone in the PI's lab, it would be helpful to systematically record this.  (It could also be called something like "lab participants".)

Currently, I'm referencing the contact within the project name (e.g., ,PI>-<Postdoc>_<organism>_RNASeq), while others may include this info in the project description.  Adding an explicit field would make it much easier to keep track of projects from large labs, and from PIs who delegate most of the responsibility to their peeps.

Thanks!

**Comment by amschaal** [comment]
Changes are now available on the test server...
