### ISSUE TITLE
Sort project status by "natural order", not alphabetically

### ISSUE THREAD

**Issue by jfass** [amschaal/glims#31]
Hey Adam, when we sort GLIMS projects by clicking on the up or down arrows, it'd be nice if they sorted in the order listed in the drop-down, which is the natural order that we go through from project start to finish. Alphabetical sorting puts completed projects right in the middle, between "Being Analyzed" and "Data Available", which is awkward to look at.

**Comment by amschaal** [comment]
The trouble with ordering statuses by status step is that the ordering is no longer alphabetical, which is inconsistent with the rest of the application.  Your suggestion to change the statuses to be numbered allows for both:
1. Beginning
2. Middle
3. End
