### ISSUE TITLE
Export project needs to include date(s)

### ISSUE THREAD

**Issue by msettles** [amschaal/glims#35]
Ideally date of creation and maybe date of "last modified", so latest log date
Also output csv produces the following "Alert" on my Mac

Excel has detected that 'projects.csv' is a SYLK file, but cannot load it. Either the file has errors or it is not a SYLK file format. Click OK to try to open the file in a different format.

**Comment by amschaal** [comment]
FYI, weird excel import issue is probably related to this:
http://stason.org/TULARC/business/spreadsheets/10-21-Why-does-Excel-claim-I-have-an-invalid-SYLK-file.html

**Comment by msettles** [comment]
Cool, so did you rename ID to something else?
