### ISSUE TITLE
Special characters inhibit searching

### ISSUE THREAD

**Issue by jfass** [amschaal/glims#36]
Matt entered an a with an umlaut over it (or is the umlaut the character that contains the letter *and* the two dots??) ... for Andreas B*a*umler's lab ... and now I can't search for the lab by typing "Ba...". Maybe prohibit special characters? Or is there an international fuzzy character conversion thingy ...?

**Comment by amschaal** [comment]
After searching around, I don't think there is a good way for me to do a "fuzzy search".  I'd probably have to detect the international character from a list and search for all combinations including the international character as well as the english equivalent.  Probably overkill, and we should just settle on not using international characters.  Maybe include their proper name in the description?
