### ISSUE TITLE
different classes of notes

### ISSUE THREAD

**Issue by msettles** [amschaal/glims#4]
Enable notes to have different 'classes'

example:
class generic
class task/todo
class bioinformatics
class dna tech core
class proteomics core

Color code?

**Comment by amschaal** [comment]
I implemented this as "tags" in the attachment submodule.  Basically, when you edit, there are tags you can check (configurable in the app settings).  The selected tags are added to the note CSS classes, and the appearance of the notes can be customized using stylesheets.  I added 2 classes to start: issue(pink), and closed(green).  We can add to or change the available tags and the resulting styles.
