### ISSUE TITLE
New feature: move directly from one project to another

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#44]
It would be great to be able to:
1. Sort projects as desired from the main project tab.
2. Click on one project to view, edit, etc.
3. Have an icon (">" ish) that allows you to move directly to the next project on the list, without having to go back to the main project page.

This is particularly desirable when there is a long list of projects that I need to page through, since each time I go back to the main page it only shows the first 10 projects, even if I expand the list to 100 and "Save Settings".

Thanks!

**Comment by amschaal** [comment]
Better solved with something more general purpose.  Added Issue #46 to address this.
