### ISSUE TITLE
Notification timestamps are wrong

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#45]
I just received a notification email (and thanks for making it obvious it came from BioBin!)

In the BioBin log, the timestamp is correct (e.g., "10/25/17 1:55 PM") but in the email text there is an offset of 7 hours (e.g., "Oct 25, 8:55PM").  Either fix or remove the timestamp from the notification email.

**Comment by amschaal** [comment]
Fixed in notification submodule
