### ISSUE TITLE
"Projects" vs "Projects"

### ISSUE THREAD

**Issue by jfass** [amschaal/glims#5]
(discussed this with Adam & Monica) ...

Why are there generic "Projects" (which Adam made to serve as "wet core" projects, with sample lists, etc.) and also a "Projects" thing for the Bioinformatics Core ("dry core" or secondary analysis projects)? These are separate concepts and separate lists right now.

Is there enough in common to merge them into one concept, with different "plug-ins" for different cores?

**Comment by amschaal** [comment]
Added the extra fields/functionality from Bioinformatics Project interface into the standard "Project" interface.  The Bioinformatics Projects pages are hidden, to be removed on further testing.
