### ISSUE TITLE
Summary List of Project with Issues (Notes)

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#57]
Currently, the only way to find an issue is to look through all the projects' notes pages. Sadly, I often overlook issues that I have created and then forgotten about.
I would like to see a list of open issues for all projects I'm subscribed to.
This could be on the Home page, Projects page, a new/revised icon in the top corner, etc.

Thanks!

**Comment by monicabritton** [comment]
This is (sort-of) OK for a start, but:
1. It seems to be a list (table?) of the text of every issue, sorted by date, without regard to project?  It's more important to me to see the name of the project than the (perhaps long) issue itself.  The only advantage of including the complete issue text would be incentive to get them cleared up/unsubscribe from projects.
2. Yes, I would much rather see a list of projects with issues, than a bunch of issues without project identification. 
3. Once I clicked on an issue, it took me to that issue, but how do I now get back to my Home page?  (Clicking on he word "Menu" at top left, or the human icon at top right didn't do this.)

**Comment by amschaal** [comment]
1. Issue text now abbreviated with the possibility to expand.  Issues are sorted by last modified date (most recent first).
2.  Issues now include project titles.
3.  Home page link added in main menu on left.
