### ISSUE TITLE
Project Logs should include changes in Time Tracker

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#63]
When someone adds hours in Time Tracker, and marks unbilled (for example), the date is included in the time tracker listing.  Then, when that line is edited, for example to change it to billed, the date is changed.  The result is that the original date when the hours were logged, is lost.

These actions are currently not noted in the Project Log, so there is often no way to tell when the hours were originally logged, only when the last edit was made.

**Comment by monicabritton** [comment]
Maybe I should change the title again to:  "Project Logs should include **_anything_** that changes the Modification date"?  Just now I got confused as to why a months-old project showed as newly-modified.  I checked the logs and there was nothing new.  But, then I realized I had probably changed the status to "Completed".  It would also be best if the log could include the userid of the person who made each modification.

**Comment by amschaal** [comment]
Created date already existed, so I exposed that via the interface.
