### ISSUE TITLE
Manager/Participants Naming Convention

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#7]
When this goes into "production" mode, will the Core Users names be first and last?  If not, what happens someday when there are two people in the system with the same first name?

**Comment by msettles** [comment]
I would prefer to go through either the UC davis or GC login eventually, as nobody off campus should never need to have access. So both should be available


Matt

**Comment by amschaal** [comment]
This was not an issue of what authentication scheme was being used, but just a shortcoming of one of the user interface elements I'm using.  I concatenated the first and last name on the server-side so that the UI widget could use that.
