### ISSUE TITLE
"Submit" and "Save" button doesn't close issue/project edit dialog box

### ISSUE THREAD

**Issue by jfass** [amschaal/glims#73]
In FireFox and Chrome, when trying to edit the name of an old project, the "Submit" button doesn't close the dialog box, so the name change doesn't stick.

When trying to submit a Note (Issue), clicking "Save" doesn't close the dialog box, but the issue does get saved (as multiple issues if I click Save multiple times!). And just now I created a real issue, then an empty issue (both by clicking save then X to close the box), then clicked on X to delete the empty issue, and it stayed while the real issue disappeared.

**Comment by monicabritton** [comment]
This wasn't a problem before Monday.  Something changed this week (though I don't see any recent commits.)  

When I just tried to test (and got same results as Joe), creation of one issue generated 14(!) Notes on my home page.  Although I may have clicked Save twice, I'm certain I didn't click it 14 times.

**Comment by amschaal** [comment]
Server was out of space.
