### ISSUE TITLE
Add Account Number Field to Project Info Page

### ISSUE THREAD

**Issue by monicabritton** [amschaal/glims#9]
Just discussed this with Matt and got his agreement.  It would be great to have a field here for the account number (doesn't need to cross check with DaFis, since it could be non-UCD).  Eventually, this may be linked to (or supplanted by) the new billing system, but in the meantime, would be a tremendous help.

Thanks,

M

**Comment by amschaal** [comment]
How about if I write this as a plugin?  It would show up as another tab, and can have any number of account related fields.  That way it doesn't get tied directly into the project model, and can have very specific functionality such as DaFIS checking.

**Comment by amschaal** [comment]
I've created a plugin which allows for an account type, account string, and description.  You can have multiple accounts for a given project.

**Comment by amschaal** [comment]
There is a setting in the configuration file that controls that.  I added "Other UC FAU".

**Comment by monicabritton** [comment]
This "Other UC FAU" does not appear as a choice, so I had to use DaFis for a UCB account.
